# -*- mode: ruby -*-
# vi: set ft=ruby :

# (c) 2014 Eyefodder, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "eyefodder/precise64-utf8"
  config.vm.host_name = 'spex'

  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true

  config.vm.synced_folder "./puppet", "/etc/puppet"
  config.vm.synced_folder 'dotfiles', '/dotfiles'
  config.vm.synced_folder '../reports', '/reports'
  config.vm.synced_folder '../client/coverage', '/app/client/coverage'
  config.vm.synced_folder '../coverage', '/app/coverage'
  config.vm.synced_folder "../", "/app", type: "rsync", rsync__exclude: [".git/", "ops/*", "reports/",  "tmp/", "log/", ".#*", "node_modules/", "app/assets/webpack/", "client/coverage/*", "coverage/"]


  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
    vb.cpus = 4
    vb.name = 'spex'
  end

  config.vm.provision 'shell', path: 'install_apt_packages.sh'
  config.vm.provision 'shell', path: 'build_ruby_from_source.sh'
  config.vm.provision 'shell', path: 'install_nodejs.sh'
  config.vm.provision 'shell', path: 'install_puppet_modules.sh'
  config.vm.provision 'shell', path: 'init_env.sh'
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = 'puppet/modules'
    puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.working_directory = "/etc/puppet"
    puppet.environment_path = "puppet/environments"
    puppet.environment = "dev"
  end

  config.trigger.before [:up, :reload], :stdout => true do
    run "mkdir -p ../reports"
    run "mkdir -p ../public/uploads"
    run "mkdir -p ../client/coverage"
    run "mkdir -p ../coverage"
    run "sh ./setup_guest_bash_profile.sh"
  end

  # FIRST RUN PROVISIONING
  config.vm.provision 'shell', path: 'init_rails_db.sh', privileged: false

  # EACH UP PROVISIONING
  config.vm.provision 'shell', path: 'prep_rails_app.sh', privileged: false, run: 'always'
end
